clear all;
clc;
disp('------------------------------------------------------------');
disp('          Program Kumpulan Rumus Volume Bangun Ruang        ');
disp('         By: Muhammad Fauzi Nur Aziz (221810101028)         ');
disp('------------------------------------------------------------');
disp('Pilihan');
disp('1. Kubus');
disp('2. Balok');
disp('3. Bola');
disp('4. Tabung');
disp('5. Kerucut');
disp('6. Limas');
disp('7. Prisma');
a=input('Pilihan Anda= ');
if a==1;
    disp([num2str(a) ' Volume Kubus= sisi^3']);
disp('-----------------------------');
disp('Penyelesaian:');
sisi=input('Masukkan sisinya= ');
Volume=sisi^3;
disp(['Volume kubus adalah ' num2str(Volume) ' cm^3']);
elseif a==2;
    disp([num2str(a) ' Volume Balok= panjang*lebar*tinggi']);
disp('-------------------------');
disp('Penyelesaian:');
panjang=input('Masukkan panjangnya= ');
lebar=input('Masukkan lebarnya= ');
tinggi=input('Masukkan tingginya= ');
Volume=panjang*lebar*tinggi;
disp(['Volume Balok adalah ' num2str(Volume) ' cm^3']);
elseif a==3;
    disp([num2str(a) ' Volume Bola= 4/3*(pi*r^3)']);
disp('-------------------------------------');
disp('Penyelesaian:');
r=input('Masukkan jari-jarinya= ');
Volume=3/4*(pi*r^3);
disp(['Volume Bola adalah ' num2str(Volume) ' cm^3']);
elseif a==4;
    disp([num2str(a) ' Volume Tabung= phi*r^2*tinggi']);
disp('---------------------------------');
disp('Penyelesaian:');
r=input('Masukkan jari-jarinya= ');
tinggi=input('Masukkan tingginya= ');
Volume=pi*r^2*tinggi;
disp(['Volume Tabung adalah ' num2str(Volume) ' cm^3']);
elseif a==5;
    disp([num2str(a) ' Volume Kerucut= 1/3*pi*r^2*tinggi']);
disp('------------------------------');
disp('Penyelesaian:');
r=input('Masukkan jari-jarinya= ');
tinggi=input('Masukkan tingginya= ');
Volume=1/3*pi*r^2*tinggi;
disp(['Volume kerucut adalah ' num2str(Volume) ' cm^3']);
elseif a==6;
    disp([num2str(a) ' Volume Limas=1/3*alas*tinggi']);
disp('-------------------------');
disp('Penyelesaian:');
alas=input('Masukkan alasnya= ');
tinggi=input('Masukkan tingginya= ');
Volume=1/3*alas*tinggi;
disp(['Luas Segitiga adalah ' num2str(Volume) ' cm^3']);
elseif a==7;
    disp([num2str(a) ' Volume Prisma = luas alas*tinggi']);
disp('---------------------------------');
disp('Penyelesaian:');
luasalas=input('Masukkan luas alasnya= ');
tinggi=input('Masukkan tingginya= ');
Volume= luasalas*tinggi;
disp(['Volume prisma adalah ' num2str(Volume) ' cm^3']);
else
     disp([num2str(a) ' Maaf Pilihan Anda Tidak Dapat di Proses']);
     disp('Silahkan untuk Memilih Pilihan yang Telah Disediakan pada List Rumus Bangun Ruang');
end